---
all:
  children:
    dns_servers:
      hosts:
        leader:
          ansible_host: 192.168.173.50
      vars:
        ansible_user: cyee

    dns_clients:
      hosts:
        bastion-vm:
          ansible_host: 192.168.173.183
        general-vm-1:
          ansible_host: 192.168.173.193
        general-vm-2:
          ansible_host: 192.168.173.104
        general-vm-3:
          ansible_host: 192.168.173.115
      vars:
        ansible_user: cyee

    alloy_servers:
      hosts:
        bastion-vm:
        general-vm-1:
        general-vm-2:
        general-vm-3:
      vars:
        ansible_user: cyee
