---
all:
  children:
    dns_servers:
      hosts:
        leader:
          ansible_host: 192.168.173.50
      vars:
        ansible_user: cyee

    alloy_servers:
      hosts:
        # Add your Alloy server hostnames here
        # bastion-vm:
        #   ansible_host: 192.168.173.X
        # general-vm-1:
        #   ansible_host: 192.168.173.X
      vars:
        ansible_user: cyee
